image: python:3.11

pages:
  stage: deploy
  script:
    - pip install shinylive
    - shinylive export app public --subdir mss-grant-lottery
  artifacts:
    paths:
      - public
  only:
    - main
